name: To do list API with Spring Workflow
on: [push]
jobs:
  To-Do-List-Api-With-Spring-Workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Run Tests
        run: ./gradlew test

      - name: Build With Gradle
        run: ./gradlew -b ci.gradle package